spring:
  profiles:
    active: core, db
  messages:
    encoding: UTF-8
  redis:
    host: 121.5.34.70
    port: 6379
    password: redis
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300
        max-idle: 16
        min-idle: 8

logging:
  level:
    root:  DEBUG
    org.springframework:  DEBUG
    org.mybatis:  DEBUG
    org.merchant.core:  DEBUG
